# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.5"
  # If you require the extended build with SCSS support, add:
  # HUGO_EXTENDED = "true"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
